### ISSUE TITLE
[Feature Request] Content Tracking / Expanded Library Statistics 

### ISSUE THREAD

**Issue by TempUser13** [OxygenCobalt/Auxio#629]
### Description

Add tracking for Artists, Albums, Songs, Playlist and Genres which could be accessed through settings or the 3 dots menu with settings and about. The Library statistics page could look like the main library UI but the content is sorted from Most Played to Least Played by default and you can pick the date period so the stats from Month 12 or from Year x etc. The times played could be displayed as another row under the artist in the UI. A play could be added if an item is played for more than 15/30 seconds. It'd be nice if you could automatically/manually export the stats which would let people move stats from device to device, sync across devices using something like Syncthing and other things. There could also be an option to ignore tracking of a specific item such as a specific song that someone uses to sleep.

### Other implementations

I'm not aware of other music players that expose this level of detail to the end user but there is Spotify where you can request your data to see every item you've played as well as the yearly Spotify Wrapped which is the main inspiration for this. 

### Benefit

Content Tracking / Expanded Library Statistics is something I don't see music players providing which gives Auxio another reason to be the go to music player especially with other features like being fully offline and multiple artist handling. It allows people to actively track and reflect on their music listening habits in a private and privacy preserving way.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Personally, I don't really gain any benefit from something like this. It's a lot of work technically (yet another database I must synchronize with the 3 or 4 others), even though I kind of know what my recent listening trends are. The problem is that it's a kind of feature I can't meaningfully use myself and catch bugs with, so it will break far more often without me realizing. Something like this only changes *if* I can forward the data to something like Spotify wrapped. Then it's actually a little useful. Although AFAIK I can't do that without just outright stream manipulation, so it's kind of a non-starter. Sorry.
